account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings

app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('adminka/',views.admin_login, name='adminka')
]

attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'
urlpatterns = [
    path('att_toggle/<str:att_id>/<str:course_code>/<str:group>/<str:course_type>/', views.att_toggle, name='att_toggle'),
    path('open_registration/<str:course_code>/<str:group>/<str:course_type>/', views.open_registration, name='open_registration'),
    path('manual_attendance/<str:course_code>/<str:is_lecture>/',views.manual_attendance,name='manual_attendance'),
    path('card_reader/',views.card_reader,name='card_reader'),
    path('reset_everything/',views.reset_everything,name='reset_everything'),
]

dashboard/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard'
urlpatterns = [
    #STUDENT
    path('', RedirectView.as_view(url='/account/login/')),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('student_courses/', views.student_courses, name='student_courses'),
    path('student_courses_specific_one/<str:course_code>/', views.student_courses_specific_one, name='student_courses_specific_one'),
    path('student_document_submission/',views.student_document_submission, name='student_document_submission'),
    
    
    path('documents/remove/<int:doc_id>', views.remove_document, name='remove_document'), 
    path('documents/download/<int:doc_id>', views.download_document, name='download_document'),
    
    path('student_documents/<str:doc_name>', views.download_document_admin, name='download_document_admin'),
    
    
    #TEACHER
    path('teacher_profile/', views.teacher_profile, name='teacher_profile'),
    path('teacher_courses/', views.teacher_courses, name="teacher_courses"),
    path('teacher_courses_specific_one/<str:course_code>/<str:course_type>/', views.teacher_courses_specific_one, name='teacher_courses_specific_one'),
    path('teacher_courses_specific_one_attendance/<str:course_code>/<str:group>/<str:course_type>/', views.teacher_courses_specific_one_attendance, name='teacher_courses_specific_one_attendance'),
    
    #ADMIN
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('dashboard.urls')),
 path('account/', include('account.urls', namespace='account')),
 path('att_registration/',include('attendance.urls'))
]

dashboard/models.py
from django.db import models
from account.models import CustomUser
from attendance.models import attendance
# Create your models here.

class SubmittedDocument(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="documents")
    description = models.TextField()
    document = models.FileField(upload_to='student_documents/')
    submitted_at = models.DateTimeField(auto_now_add=True)
    from_date = models.DateTimeField(blank=False)
    to_date = models.DateTimeField(blank=False)
    ACCEPTED_CHOICES = [
        (0, 'Not Checked'),
        (1, 'Accepted'),
        (2, 'Rejected')
    ]
    accepted = models.IntegerField(default=0, choices=ACCEPTED_CHOICES)
    def __str__(self):
        return f"{self.student.id} -  {self.document.name}"
    
    def update_attendance(self):
        if self.accepted == 1:  # Only update if the document is accepted
            attendance.objects.filter(
                student_id=self.student.id,
                date__range=[self.from_date, self.to_date],
                status=2  # Assuming 2 means 'absent'
            ).update(status=0)  
    
    
            

dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError

def validate_file_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError('Only PDF files are allowed.')


class DocumentSubmissionForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}), required=True)
    document = forms.FileField(required=True,validators=[validate_file_extension])

dashboard/views.py
from django.http import FileResponse, Http404, HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from attendance.models import course, attendance, specific_course, teachers_courses, students_courses
from dashboard.models import SubmittedDocument
from account.models import Teacher, Student
from .forms import DocumentSubmissionForm
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.contrib import messages
import math

#STUDENT
@login_required
def student_profile(request):
    return render(request, 'dashboard/profile_student.html',{'status1':"active",'status2':"",'status3':""})
    
@login_required
def student_courses(request):
    course_codes = []
    course_info = [] # it will contain array [p, present, absent]
    gen_courses_info = []
    
    current_date_time = timezone.localtime(timezone.now(), timezone=timezone.get_fixed_timezone(300))
        
    current_date = current_date_time.date()
    
    #Geting into students_courses table 
    specific_course_ids_of_a_student = students_courses.objects.filter(student_id=request.user.student.id).values_list('specific_course_id', flat=True)
    
    for id_specific_course in specific_course_ids_of_a_student:
        # inside students_courses table and getting into specific courses table  
        course_of_student = specific_course.objects.filter(specific_course_id=id_specific_course).first()
        # checking each specific course for attendance
        if course_of_student.course_code in course_codes:
            for i, existing in enumerate(course_codes):
                if existing == course_of_student.course_code:
                    
                    present=len(attendance.objects.filter(student_id=request.user.student.id, specific_course_id=id_specific_course,status=1, date__lte=current_date))
                    P=len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=0,date__lte=current_date))
                    absent=len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=2,date__lte=current_date))
                    
                    course_info[i][0]=course_info[i][0]+P
                    course_info[i][1]=course_info[i][1]+present
                    course_info[i][2]=course_info[i][2]+absent
                    break
        else:
            course_codes.append(course_of_student.course_code)
            present=len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=1,date__lte=current_date))+len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=3))
            P=len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=0,date__lte=current_date))
            absent=len(attendance.objects.filter(student_id=request.user.student.id,specific_course_id=id_specific_course,status=2,date__lte=current_date))
            course_info.append([P,present,absent])
    
    for i, code in enumerate(course_codes):
        course_obj = course.objects.filter(course_code=code).first()
        gen_courses_info.append({
            "course_code":code,
            "course_name":course_obj.course_name,
            "credits":course_obj.credits,
            "ECTS":course_obj.ECTS,
            "hours":course_obj.hours,
            "present": course_info[i][1],
            "absent": course_info[i][2],
            "P":course_info[i][0],
            "absens_persentage": math.ceil((course_info[i][2]/course_obj.hours)*100)
        })
    
    return render(request, 'dashboard/courses_student.html', {'student_courses': gen_courses_info, 'status1':"",'status2':"active",'status3':""})

@login_required
def student_courses_specific_one(request,  course_code=None):
    current_date_time = timezone.localtime(timezone.now(), timezone=timezone.get_fixed_timezone(300))
    current_date = current_date_time.date()
    
    specific_course_ids_of_a_student = students_courses.objects.filter(student_id=request.user.student.id).values_list('specific_course_id', flat=True)
    course_obj = course.objects.filter(course_code=course_code).first()
    course_item = {}
    
    course_item['course_code']=course_obj.course_code
    course_item['course_name']=course_obj.course_name
    
    course_code_matched_ids_l = []
    course_code_matched_ids_p = []
    
    practice_groupe = None
    lecture_groupe = None
    
    for specific_course_id in specific_course_ids_of_a_student:
        course_of_student = specific_course.objects.filter(specific_course_id=specific_course_id).first()
        if course_of_student.course_code==course_code:
            if course_of_student.is_lecture==False:
                course_code_matched_ids_p.append(specific_course_id)
                practice_groupe=course_of_student.group
            else :
                course_code_matched_ids_l.append(specific_course_id)
                lecture_groupe=course_of_student.group
    
    course_item['groupe']={'practice':practice_groupe,'lecture':lecture_groupe}
    
    lecturer_id =teachers_courses.objects.filter(specific_course_id=course_code_matched_ids_l[0]).first().teacher_id
    lecturer = Teacher.objects.filter(id=lecturer_id).first()
    
    course_item['lecturer']=lecturer.first_name+" "+lecturer.last_name
    course_item['lecturer_status']=lecturer.status
    #####################################
    calculated_time = (specific_course.objects.filter(specific_course_id=course_code_matched_ids_l[0]).first().registration_deadline- timezone.now()).total_seconds()
    if calculated_time<0 :
        calculated_time = 0
    course_item['lecture_attendance_time']=calculated_time
    #####################################
    lecture_attendances = []
    attendances = attendance.objects.filter(student_id=request.user.student.id,specific_course_id__in=course_code_matched_ids_l)
    
    for att in attendances:
        if att.date<=current_date:
            start_time= specific_course.objects.filter(specific_course_id=att.specific_course_id).first().course_start_time
            lecture_attendances.append({
                "week":att.date,
                "status":att.status,
                "start_time":start_time
            })
    
    lecture_attendances = sorted(lecture_attendances, key=lambda att: att['week'])
    
    if len(course_code_matched_ids_p)==0:
        return render(request, 'dashboard/course_specific_student.html', {'course': course_item,'lecture_attendances':lecture_attendances,'status1':"",'status2':"active",'status3':""})
    else :
        practice_attendances = []
        attendances = attendance.objects.filter(student_id=request.user.student.id,specific_course_id__in=course_code_matched_ids_p)

        practice_teacher_id =teachers_courses.objects.filter(specific_course_id=course_code_matched_ids_l[0]).first().teacher_id
        practice_teacher = Teacher.objects.filter(id=practice_teacher_id).first()
        
        course_item['practice_teacher']=practice_teacher.first_name+" "+practice_teacher.last_name
        course_item['practice_teacher_status']=practice_teacher.status

        #####################################
        calculated_time = (specific_course.objects.filter(specific_course_id=course_code_matched_ids_p[0]).first().registration_deadline- timezone.now()).total_seconds()
        if calculated_time<0 :
            calculated_time = 0
        course_item['practice_attendance_time']=calculated_time
        #####################################

        
        for att in attendances:
            if att.date<=current_date:
                start_time= specific_course.objects.filter(specific_course_id=att.specific_course_id).first().course_start_time
                practice_attendances.append({
                    "week":att.date,
                    "status":att.status,
                    "start_time":start_time
                })
        practice_attendances = sorted(practice_attendances, key=lambda att: att['week'])
        return render(request, 'dashboard/course_specific_student.html', {'course': course_item,'lecture_attendances':lecture_attendances,'practice_attendances':practice_attendances,'status1':"",'status2':"active",'status3':""})

@login_required 
def student_document_submission(request): 
    student_courses = []
    specific_course_ids_of_a_student = students_courses.objects.filter(student_id=request.user.student.id).values_list('specific_course_id', flat=True)
    unique = []
    for id_specific_course in specific_course_ids_of_a_student: 
        course_of_student = specific_course.objects.filter(specific_course_id=id_specific_course).first()
        cours = course.objects.get(course_code=course_of_student.course_code)
        group = str(course_of_student.group)
        if course_of_student.is_lecture:
            group += 'N'
        else:
            group += 'P'
        student_course = {
                'specific_course_id': course_of_student.specific_course_id,
                'course_code': cours.course_code,
                'course_name': cours.course_name,
                'group': group,
                
            }
            # Adding the dictionary to the list
        repr = str(cours.course_code) + str(cours.course_name) + group 
        if repr not in unique:
            student_courses.append(student_course)
            unique.append(repr)
    
    documents = SubmittedDocument.objects.filter(student_id=request.user.student.id)
    context = {'status1':"",'status2':"",'status3':"active",'student_courses': student_courses, "documents": documents}
    
    if request.method == 'POST': 
        form = DocumentSubmissionForm(request.POST, request.FILES) 
        if form.is_valid():    
            new_document = SubmittedDocument() 

dashboard/templates/dashboard/course_specific_student.html
{% extends "dashboard/student_base.html" %}
{% block content %}
<div class="specific_course">
    <div class="hirarchi">
        <h3 onclick="window.location.href='{% url 'dashboard:student_courses'%}'" >&nbsp;> COURSES</h3><h3 onclick="window.location.href='{% url 'dashboard:student_courses_specific_one' course_code=course.course_code %}'" >&nbsp;> {{ course.course_code}} - {{ course.course_name }}</h3>  
    </div>

    <div class="lecture">
        
        <div class="teacher_info">
            <h3>{{ course.course_code}} - {{ course.course_name }}</h3>
            <p>{{course.groupe.lecture}}-N {{course.lecturer}}, {{course.lecturer_status}}</p>
        </div>
        
        <table class="attendance_table" >
            <thead>
                <tr>
                    <th></th>
                    <th>Date</th>
                    <th>Hour</th>
                    <th>Attendance</th>
                    <th>Place</th>
                </tr>
            </thead>
            <tbody>
                {% for attendance in lecture_attendances %}
                <tr>
                   <td>{{ forloop.counter }}</td>
                   <td>{{ attendance.week }}</td>
                   <td>{{ attendance.start_time|time:"H:i"  }}</td>
                   <td>{% if attendance.status == 1 %}✅{% elif attendance.status == 2 %}❌{% elif attendance.status == 3 %}M{% else %}P{% endif %}</td>
                   <td>F301</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if course.lecture_attendance_time > 0 %}
            <form class = "form" action="{% url 'attendance:manual_attendance' course_code=course.course_code is_lecture=1 %}"onsubmit="showLoadingOverlay()" method="post" id="login-form">
                {% csrf_token %}
                <input type="submit" class="btn_for_attendance" value="Register Attendance"/>
            </form>
        {% else %}
            <form class="form"  method="post" id="login-form">
                {% csrf_token %}
                <input type="submit" class="btn_for_attendance" style="background-color: rgba(128, 128, 128, 0.5); color: white; cursor: not-allowed; opacity: 0.5;" value="Register Attendance" disabled/>
            </form>
        {% endif %}
    </div>
    {% if practice_attendances %}
    <div class="practice">
        
        <div class="teacher_info">
            <h3>{{ course.course_code}} - {{ course.course_name }}</h3>
            <p>{{course.groupe.practice}}-P {{course.practice_teacher}}, {{course.practice_teacher_status}}</p>
        </div>    

        <table class="attendance_table">
            <thead>
                <tr>
                    <th></th>
                    <th>Date</th>
                    <th>Hour</th>
                    <th>Attendance</th>
                    <th>Place</th>
                </tr>
            </thead>
            <tbody>
                {% for attendance in practice_attendances %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ attendance.week }}</td>
                    <td>{{ attendance.start_time|time:"H:i"  }}</td>
                    <td>{% if attendance.status == 1 %}✅{% elif attendance.status == 2 %}❌{% else %} P {% endif %}</td>
                    <td>F301</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if course.practice_attendance_time > 0 %}
            <form class = "form" action="{% url 'attendance:manual_attendance' course_code=course.course_code is_lecture=0 %}"onsubmit="showLoadingOverlay()" method="post" id="login-form">
                {% csrf_token %}
                <input type="submit" class="btn_for_attendance" value="Register Attendance"/>
            </form>
        {%else%}
            <form class="form"  method="post" id="login-form">
                {% csrf_token %}
                <input type="submit" class="btn_for_attendance" style="background-color: rgba(128, 128, 128, 0.5); color: white; cursor: not-allowed; opacity: 0.5;" value="Register Attendance" disabled/>
            </form>    
        {% endif %}
    </div>
    {% endif %}
</div>
{% endblock content %}

dashboard/templates/dashboard/course_specific_teacher.html
{% extends "dashboard/teacher_base.html" %}
{% block content %}
<div class="gen_courses_info">

    <div class="section_info"> 
        <div style="display:flex;flex-direction:row;">
            <h3 onclick="window.location.href='{% url 'dashboard:teacher_courses'%}'" >&nbsp;> COURSES</h3><h3 onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one' course_code=course_code course_type=course_type %}'" >&nbsp;&nbsp;> {{course_code}} - {{ course_name }} </h3>  
        </div> 
        <h2>COURSES</h2>        
    </div> 
    <section class="attendance_container">
        <table class="attendance_table">
            <thead>
                <tr class="header-row">
                    <th>Code</th>
                    <th>Group</th>
                    <th>Type</th>
                    <th>Taking Attendance</th>
                </tr>
            </thead>
            <tbody>
                {% for course in teacher_courses %}
                        <tr > 
                        <td onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one_attendance' course_code=course.course_code  group=course.group course_type=course_type %}'">{{ course.course_code }}</td>
                        <td onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one_attendance' course_code=course.course_code  group=course.group course_type=course_type %}'">{{ course.group }}</td>
                        <td onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one_attendance' course_code=course.course_code  group=course.group course_type=course_type %}'">{{ course_type }}</td>
                        <td style="display:flex;align-items:center;justify-content:center;">
                            {% if course.registration_time_left == 0 %}
                                <h3 class="week_att" onclick="sendtheform({{course.group}});">
                                    No
                                    <form action="{% url 'attendance:open_registration' course_code=course.course_code group=course.group course_type=course_type %}" method="post" id="toggle-form-{{course.group}}" style="display: none;">
                                        {% csrf_token %}
                                        <input type="text" name="status" id="status-input" readonly>
                                    </form>
                                </h3>
                            {% else %}
                                <h3 class="week_att">
                                    Yes
                                </h3>
                                <script>
                                    // Reload the page after course.registration_time_left seconds
                                    setTimeout(function() {
                                        location.reload();
                                    }, {{ course.registration_time_left }} * 1000); // Convert seconds to milliseconds
                                </script> 
                            {% endif %}
                        </td>    
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    <section>
</div>
<script>
    function sendtheform(counter) {
        console.log(counter)
        const form = document.getElementById(`toggle-form-${counter}`);
        form.submit();
    }
</script>
{% endblock content %}

dashboard/templates/dashboard/course_specific_teacher_attendance.html
{% extends "dashboard/teacher_base.html" %}
{% block content %}
<div class="gen_courses_attendance_info">

    <div class="section_info"> 
        <div style="display:flex;flex-direction:row;">
            <h3 onclick="window.location.href='{% url 'dashboard:teacher_courses'%}'" >&nbsp;> COURSES</h3>
            <h3 onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one' course_code=course_code course_type=course_type %}'" >&nbsp;&nbsp;> {{course_code}} - {{ course_name }} </h3>  
            <h3 onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one_attendance' course_code=course_code  group=group course_type=course_type %}'" >&nbsp;&nbsp;> Group - {{group}} </h3>  
        </div> 
        <h2>COURSES</h2>        
    </div> 
    <section class="attendance_container">
        <table class="attendance_table">
            <thead>
                <tr class="header-row">
                    <th>#</th>
                    <th>Student name</th>
                    {% for week in weeks %}
                        {% for hour in week %}
                            <th>W&nbsp;{{ forloop.parentloop.counter }}&nbsp;|&nbsp;{{ hour|time:"H:i" }}</th>
                        {% endfor %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr > 
                        <td>{{ forloop.counter }}</td>
                        <td>{{ student.name  }}</td>
                        {% for attendance in student.attendances %}
                            {% for hourly in attendance %}

                                <td class="att_status_container" onclick="toggleStatus({{ hourly.attendance }});">
                                    <form action="{% url 'attendance:att_toggle' att_id=hourly.attendance course_code=course_code group=group course_type=course_type %}" method="post" id="toggle-form-{{ hourly.attendance }}" style="display: none;">
                                        {% csrf_token %}
                                        <input type="text" name="status" id="status-input" readonly>
                                    </form>
                                    {% if hourly.status == 1 %}
                                        ✅
                                    {% elif hourly.status == 2 %}
                                        ❌
                                    {% elif hourly.status == 3 %}
                                        M
                                    {% else %}
                                        P 
                                     {% endif %}
                                </td>

                            {% endfor %}
                        {% endfor %}    
                    </tr >
                {% endfor %}
            </tbody>
        </table>
    <section>
</div>
<script>
    function toggleStatus(counter) {
        console.log(counter)
        const form = document.getElementById(`toggle-form-${counter}`);
        form.submit();
    }
</script>
{% endblock content %}

dashboard/templates/dashboard/courses_teacher.html
{% extends "dashboard/teacher_base.html" %}
{% block content %}
<div class="gen_courses_info">

    <div class="section_info"> 
        <div >
            <h3 onclick="window.location.href='{% url 'dashboard:teacher_courses'%}'" >&nbsp;> COURSES</h3>  
        </div> 
        <h2>COURSES</h2>        
    </div> 
    <section class="attendance_container">
        <table class="attendance_table">
            <thead>
                <tr class="header-row">
                    <th>Code</th>
                    <th>Course name</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                {% for course in teacher_courses %}
                        <tr onclick="window.location.href='{% url 'dashboard:teacher_courses_specific_one' course_code=course.course_code course_type=course.course_type  %}'"> 
                        <td>{{ course.course_code }}</td>
                        <td>{{ course.course_name }}</td>
                        <td>{{ course.course_type }}</td>    
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    <section>
</div>
{% endblock content %}

dashboard/templates/dashboard/document_submission_student.html
{% extends "dashboard/student_base.html" %}
{% block content %}
<div class="document_submission">
    
    <div class="hirarchi">
        <h3 onclick="window.location.href='{% url 'dashboard:student_document_submission'%}'" >&nbsp;SERVICES</h3>
    
    </div>
    
    <div class="form_container">
        <form class="file_submission_form" method="post" enctype="multipart/form-data">
            <h2>Submit Documents</h2>
            {% csrf_token %}
            
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea name="description" id="description" class="form-control" rows="4" required></textarea>
            </div>

            <label for="from_date" style="display: inline-block; margin-right: 10px;">From Date:</label>
             <input type="date" name="from_date" id="from_date" style="display: inline-block;">


            <label for="to_date" style="display: inline-block; margin-right: 10px;">To Date:</label>
            <input type="date" name="to_date" id="to_date"  style="display: inline-block;">
            
            
            <div class="form-group">
                <label for="document">Upload :</label>
                <input type="file" name="document" id="document" class="form-control-file" required>
            </div>

            <button type="submit" class="submit_document_button">Submit</button>
            <br>
            {% for doc in documents %}
            <li style="display: flex;text-align: left;">
                <div>
                    <a href="{% url 'dashboard:download_document' doc.id %}">
                    {{ doc.document.name|cut:"student_documents/" }}
                    </a> - Uploaded on: {{ doc.submitted_at }}
                    <a href="{% url 'dashboard:remove_document' doc.id %}">Remove</a>
                </div>
                <div>
                    &nbsp;Status:
                    {% if doc.accepted == 0 %} 
                        Not Checked 
                    {% elif doc.accepted == 1 %} 
                        Accepted 
                    {% else %} 
                        Rejected 
                    {% endif %}
                </div>
            </li>
            {% endfor %}

            {% if error %}
                <div id="error-messages" class="error-messages">
                    <p style="color: red ;text-align: center; font-size: 2.2vh; ">{{ error }}</p>
                </div>
            {% elif success %}
                <div id="error-messages" class="error-messages">
                    <p style="color: blue;text-align: center; font-size: 2.2vh; ">{{ success }}</p>
                </div>
            {% endif %}
        </form>
    </div>

</div>
<script>
    setTimeout(function() {
        
        var errorMessages = document.getElementById('error-messages');
        
        if (errorMessages) {
            errorMessages.style.display = 'none';
        }
    
    }, 6000);  // 6 seconds
    
</script>
{% endblock content %}

dashboard/templates/dashboard/student_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Profile</title>
    <link rel="stylesheet" href="{% static 'css/student_base.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/image.png' %}">
    <style>
        @font-face {
        font-family: 'gilroy-600';
        src: url('{% static "fonts/Gilroy_Qaz/Gilroy-Semibold 2.ttf" %}') format('truetype');
        font-weight: normal;
        font-style: normal;
        }
        @font-face {
            font-family: 'sduBold';
            src: url('{% static "fonts/sdu.otf" %}') format('opentype');
        }
    </style>
</head>

<body>
    {% with student=request.user.student %}
        <div class="navigator">
            <img src="{% static 'img/image.png' %}" alt="Happy University Logo">
            <ol >
                <li id="PROFILE" class="{{status1}}" onclick="window.location.href='{% url 'dashboard:student_profile' %}';"><p>PROFILE</p></li>
                <li id="COURSES" class="{{status2}}" onclick="window.location.href='{% url 'dashboard:student_courses' %}';"><p >COURSES</p></li>
                <li id="CERTIFICATES" class="{{status3}}" onclick="window.location.href='{% url 'dashboard:student_document_submission' %}';"><p >SERVICES</p></li>
            </ol>
            <form method="post" action="{% url 'account:logout' %}">
                {% csrf_token %}
                <input type="submit" class="logout_button" value="LOG OUT">
            </form>
        </div>
        {% block content%}{% endblock content %}
    {% endwith %}
</body>